feathersjs/feathers-hooks

- .editorconfig
- LICENSE
- lib/after.js
- lib/before.js
- lib/commons.js
- lib/hooks.js
- lib/utils.js
- test/after.test.js
- test/before.test.js
- test/utils.test.js
This pull request is a bigger refactoring that fixes the hook execution order (closes #13) and adds support for before-all and after-all hooks (closes #11). New tests added and old tests didn't need to be changed (so we can assume backwards compatibility).
> Refactoring to fix hook execution order and all-hooks

- lib/commons.js
- test/after.test.js
- test/before.test.js
This pull request makes sure that hooks don't loose the service as the context. Closes #17.
> Make sure hooks and service methods keep their context

- package.json
- src/after.js
- src/before.js
- src/commons.js
- test/after.test.js
- test/before.test.js
`next()` should only be called once in a hook and not preventing it led to some hard to debug errors. This now throws an error.
> Prevent next from being called multiple times

- README.md
- examples/authorization.js
- examples/timestamp.js
- package.json
- src/after.js
- src/before.js
- src/commons.js
- test/after.test.js
- test/before.test.js
- test/hooks.test.js
This pull request is a larger refactoring that allows service methods that return promises and turns hooks into promise chains. They can now also be used like this:
```js
app.service('todos').before({
create(hook) {
if(!hook.data.text) {
throw new Error('Text has to be provided');
}
hook.data.text = data.text.substring(0, 255);
}
});
```
Closes #28
> Refactoring for hooks to use promises and promise chains

- src/before.js
- src/hooks.js
- test/after.test.js
- test/before.test.js
I think this is the most elegant place to add the app object so that it's always available in hooks, even on internal requests (which don't pass through one of the providers).
The next issue that will surface is probably circular requests where service A requests data from B, B from C, and C from A.
> Adds the app object at hook.app.

- src/before.js
- src/hooks.js
- test/before.test.js
- test/bundled.test.js
This allows a `before` hook to set the result of the hook object which will skip the original method call. This is useful for things like overriding methods or fall-through caching.
> Allow before hooks to set the result which will skip service method

- .jshintrc
- src/bundled.js
- test/bundled.test.js
Making it so that remove hook only runs when `params.provider` is set (ie. a call over sockets or rest happened).
> Params provider

- package.json
- src/bundled.js
- src/hooks.js
- test/bundled.test.js
`.pluck` is like `.remove` but it includes only the fields it's given, rather than excluding them. Fixes #50. Also including a quick fix for `npm compile` on Windows.
> Add "pluck" bundled hook

- src/bundled.js
- src/hooks.js
- test/bundled.test.js
It looks like this:
```js
app.service('todos').after({
create: hooks.populate('user', { service: 'users' })
});
app.service('todos').create({
text: 'A todo',
user: 10
}).then(todo => {
assert.deepEqual(todo, {
text: 'A todo',
user: { id: 10, name: 'user 10' },
id: 0
});
done();
}).catch(done);
```
```js
app.service('todos').after({
create: hooks.populate('user', {
service: 'users',
field: 'userId'
})
});
app.service('todos').create({
text: 'A todo',
userId: 10
}).then(todo => {
assert.deepEqual(todo, {
text: 'A todo',
userId: 10,
user: { id: 10, name: 'user 10' },
id: 1
});
done();
}).catch(done);
```
Closes #17
> Adding functionality and tests for the populate hook

- src/bundled.js
- src/hooks.js
- test/bundled.test.js
These bundled hooks serve to remove and pluck query params.
Picture a situation in which you have user resources with passwords
```
[
{
username: "foo",
password: "password"
}
]
```
You shouldn't be able to have a `password: "password"` query parameter - it would be a security hole. You can either `.pluck('username')` to only permit querying based on username, or `.remove('password')` to permit querying on anything other than password.
Not sure if the tests on the two of these are sufficient or not. Let me know.
> Query bundled hooks

- src/bundled.js
- test/bundled.test.js
This solves an issue when you have a hook:
```javascript
all: [
hooks.lowerCase('email', 'username')
]
```
and you do not receive data that are supposed to be lowercased. Currently it throws `TypeError: Cannot call method 'toLowerCase' of undefined`.
> Do not throw an error when a field that is supposed to be lowercased is undefined

- src/bundled.js
- test/bundled.test.js
This fixes #74 where relationships that were arrays of identifiers were being passed to `service.get` as an id instead of mapping over each id.
> Handle array population

- src/bundled.js
- test/bundled.test.js
Currently if you use populate and call with a query (for example `.find({query: {something: true}})`, the query is kept for the populate request to .get, which can cause side effects in some drivers (knex) making the .get be effectively `{id: item.id, something: true}` (which can return nothing when it should return something). This removes the query from the .get params
Also included a fix for #80 as it helped with the test
> Remove query in populate

- src/bundled.js
- test/bundled.test.js
Issue #79 asked for the ability to delete deeply nested attributes in a bundled hook like:
```js
hooks.remove("user.password")
```
I added functionality which checks if the object has the field.
And also a separate function to remove the field
I needed this for myself so I thought I could share and also get a review on my code
> Add ability to delete deeply nested attributes in bundled hooks

- src/commons.js
- src/hooks.js
- test/after.test.js
- test/onerror.test.js
This allows to register `onError` hooks the same way as `before` and `after` hooks:
```js
const app = feathers().configure(hooks()).use('/dummy', {
get() {
return Promise.reject(new Error('Something went wrong'));
}
});
const service = app.service('dummy');
service.onError(function(hook) {
// hook.type === 'onError'
// hook.error === Error('Something went wrong')
throw new Error('This is another error');
});
service.get().catch(e => console.error(e));
```
Closes #83
> onError hooks functionality

- src/commons.js
- src/hooks.js
- test/error.test.js
This pull request adds a `.hooks` service method that supports any kind of hook (without having to add each as a service method itself). `service.before` and `service.after` are kept for backwards compatibility. They can be used and chained like all hooks already used. Basically any `service.before(anything);` becomes `service.hooks({ before: anything })`. Some examples:
```js
const todos = app.service('todos');
// before and after multiple hooks
todos.hooks({
before: {
all: [ beforeAllHooks ],
create: [ beforeCreate ]
// etc.
},
after: {
all: [],
create: []
// etc.
},
error: { // new on error hooks
all: [],
create: []
// etc.
}
});
// before create single hook
todos.hooks({
before: {
create
}
});
// before all hook
todos.hooks({
before(hook) {
}
});
```
> Implement .hooks service method

- package.json
- src/commons.js
- src/hooks.js
- test/app.test.js
- test/bundled.test.js
This pull request adds `app.hooks` which allows to register global `before`, `after` and `error` hooks that run for every service.
__Note:__ App `before` hooks will always run before all other service `before` hooks. App `after` and `error` hooks will run after all service specific `after` and `error` hooks.
For example logging the duration of every service method execution can be done like this:
```js
app.hooks({
before(hook) {
hook.start = new Date().getTime();
},
after(hook) {
const duration = new Date().getTime() - hook.start;
console.log(`${hook.method} execution took ${duration}ms`);
}
});
```
A global service error handler that logs the error can look like this:
```js
app.hooks({
error(hook) {
console.error(`Error in ${hook.method}`, error);
}
});
```
Also closes #119
> app.hooks global hooks

- package.json
- src/hooks.js
- test/hooks.test.js
Adds to the hook object:
- `hook.path` which contains the current service path. This is implemented as a getter so it only runs when actually needed.
- `hook.service` which is the same as `this` in a hook but it seemed like people got tripped up by it and `this` also does not work when using arrow functions.
> Adding hook.path and hook.service

- index.d.ts
Main goal is to add `before()` and `after()` methods to service instances, but ended up adding more things.  
Right now, before and after must be used as methods, and not properties.  Could be improved later.
Related to #135 
This gist:  https://gist.github.com/harangue/9d4ed79118e2656f5e3d2d699296ed36 is the main source.
> Additional hook typedefs

- src/hooks.js
Fixes issue with __hooks being overwritten when service is re-used.
```
app.use('/me/projects', app.service('/projects'))
```
Throws an error
```
Object.defineProperty(target, '__hooks', {
^
TypeError: Cannot redefine property: __hooks
```
Hooks should not try to redefine that object if it already exists.
> Fixed issue with __hooks being overwritten when reusing service

- index.d.ts
> TypeScript: HookProps.type: add 'error'

- README.md
This is a very minor change. I've been working on a feathers-based API for the last few weeks (it's awesome!) and have noticed a few links still pointing to the legacy documentation. I assume you want them all to point to the latest documentation so here is a pull-request to take care of that for this README.
> Update README to point at new documentation location

- src/hooks.js
- test/error.test.js
For feathersjs/feathers-hooks#151
This is (mostly) just copying the necessary parts and test from @daffl's fix found in the main project:
https://github.com/feathersjs/feathers/pull/621/files
I have a create user (sign up) service that returns just the email that was entered and we show a message that says something like `Email sent! Please check ${response.email} for additional information.`
However, if the user already exists then the service returns an error - which is good if the server or an admin user runs it.
BUT if the request is from a non-admin end user, we need to return the original non-error reply as if the email didn't exist. (so we don't leak information to anyone maliciously using the form about who's registered)
In order to do that in a clean way, we need to conditionally …
> Allow errors to be swallowed in error hooks

- index.d.ts
TypeScript 2.5.2 in strict mode throws many errors on the built-in `index.d.ts` declarations. It doesn't seem possible to prevent TypeScript from throwing these errors (the `exclude` option doesn't work). I feel it's bad form to "ignore" errors, so I'd rather seem them patched in the upstream source.
> Fix TypeScript declarations.
